apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:oR4JDXspaaecMpHJDpbAgSkzDhyU+Wa6RrrXBjemwF6RcIeX,iv:vDLg/uw4uEb44xX6ZvfQ6TV4TSQEv2nHQFwCyN3tP1w=,tag:i317Ihggkxcdq8R2av4t4A==,type:str]
    credentials.json: ENC[AES256_GCM,data:scwJdJHKh/pTPXeuDSykadJZ129MmV+RPWDoWuC7GjqlApWpiQ9tcBSXddDgm/k83HvwE5336wnMIEtv788ExWQErQt35IYpEo7qbwZ9RxS50kR78varE+T4e4Ws+VvzYNJU4rWzSKaVdYqwlqYUnO7Z43an5UtMoFeEgTyx/WRA7NWNekdk8RnF4+G3ja6kpZDH1Y23nVhU0o2qjeHZDVy0swWzQAvtpO5BHiao0w==,iv:TTYR3gjIegG7ijxS4McbR1PJrAaVsHfd5l+GTlv4g2A=,tag:ttLvzEjyMyFpTQztoXei0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNkZlSnJ2cExBT0huSTlT
            OUgySGdzcU1LTVNsVW50V2pnV3VBcHBPc2dNCjJ4QnpkR3hIZTNnMkFWY2w3VGw2
            Zi9EUk1KTGZicS9UQm5PZkZOUFhNOEkKLS0tIEJjbFBHZ2k0WENSQ3k0d09ZUFNQ
            Y3dSanFPVWxObnhZeEpsOWpaSmJacUkKa1CeEziox+bI6afwck1sW5lcCBBDZGs3
            6sUVIxTZLux84BFmQlyLARNONygTb93w+T8gYwcb4mYGt8yItE3kTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:17:21Z"
    mac: ENC[AES256_GCM,data:uzZ9xPcpZpN9eNnFJPcL/0ufl9+UbzlOBvwbEXiJi4KpCQUCb4kiChVT5u6KmL44FGuOEbu/njxWJ9dHuC8bHK1T+E+4HNEL4zjoQSIJ1P79xtUbHopN2VEY3avERjbx+e7fYKBYO8oiiEL79T7mJic04r9/00E/MJt9D08gqaE=,iv:YgObSpqCLXaa6SpJIZH/cKe1zHJRG8r9kWtA0RR1tmI=,tag:9UASgyJkmyoSEUWUXUu2Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
