apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YScTaKS3rJ/TkF/NnqFHYeYSPY9KTuVJPClBkV77nlwnSJw35Nhqlw==,iv:1Y1r5vyOJQUBEojHOOMCT5JPhvb9PNz2PSuHC1ZCGFo=,tag:6fSVcuzXgdiTBglTiMdBjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbDcrNHIzUGR1aklpK2E3
            NStpakkzbWMzS0d5T1M4b2tCek1IYVJhcUdzCmdyRkV4ZTBWTzdHTUZBVzVPNk9h
            TVhwMHZXbVFBZnNDL2IzV3lIWU92S0kKLS0tIEZLTlJCUmNGaUREZEtYMzJPeXBP
            ZHgzUGhPL1YwaEVhY1FuSzZZQTMveDQKLb7k8I21DozP1pWYELBufCdNqNysCe8O
            S8Up7nOePklQwRjwJCx/hKvoMMpy/5TLk67NjsUg2Qvm2d4o6kFHSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:17:21Z"
    mac: ENC[AES256_GCM,data:qtyVkF8PvbCDCEycaJNRxAqSJTdGXuuT6GzXo2N0URUi0YPYyerpZuP/+UmTHyq+xhIBmt2Gd2NA9CNsdYuQlLGB/eHykMLCgqXw8eUmM36yzlpHDgdovXYwHRzTk1Rz0fr6HXbh7NQN9japz65e96DMgGzWprG0sQuM43lbbaw=,iv:XS/SLGm9W9s78DLEx7vhLW0+QvunSoB8X4HveA1q8qU=,tag:KYVrl3zGADU29Js3Ih+kUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
