apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5nNJQLybBuWv,iv:wkZsct00StkzGEJwRD0E9yG+B+SPE2bWnJqoGwCTHvQ=,tag:LfSwIlLysXUD5kmpYBGVew==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/rIXCKCAI1sul4cUYIWF9Hkr7Fa+,iv:uT/8A7HMShgWUR78Tbv9HVcITL9VUb8gj1CgDAmXM68=,tag:f9qUmWCWJ1OQhccjDvO80Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TqG849MfRJ1ZkIrPd6olIKD53BQ0GAdQXx2lxFiGupnEMDvE,iv:lfauNk7KvfhiYgnPM9uJPOpHuRjJ14EfA5Tu5ZK8fVQ=,tag:urr3mraQi9vvN4EsC2cL/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ25aWHhXMUxha25SR0to
            YkVyRWhSeElPRGxwUVVJeTFyb01WdWZ2Mnk0CjdLbHRHRks3T2FLNzc1dmszaFJX
            M2ZVQ09kakFDak9qTHQySis1ZHpNNEUKLS0tIGVWZ3N5bU83SjBVa0ZEQ1g4bGgw
            SmpzbXNGSzRXeVJiR3dxdHFrdmk5RzgKQg47NbFfamPaiYgIrlFIGl18siButmvQ
            /PTP8flqXNFgG0db0EGel57pWbx0YXDDuC2QDTMX3RtzaLxx3M8dRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T15:40:36Z"
    mac: ENC[AES256_GCM,data:ZxUhnRzVBuwDET3K+xAJynY29ft7NRJLfwBqErksPOax9goE6/E8kdktZUH/4Kd4YY331JAs+w1enk0FBDXTbHWlUE3jNrgrRmFODAqaXCENFoPwWLNF2Eqw/z5Xoj/G1mDdwNQAeT22Q18qK3PiOWnMR1qfXzNOt9KIwddSJhI=,iv:ftqYDfda6v5c+4xz+v23UWEWhPYb4Tnx2m5FPWJBkUE=,tag:3VDzhEnekCBzqIuL2Ja2XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
