apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/89WSvxiIihVTpUI,iv:5NCvZTaltPt8/SX1Sq4kqX8H0hqlhm1RbYuQ/DYW7tA=,tag:9GoOOSepeOCUYdAObOF5KQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oZqUDzRgYVHyosjlhh8Pan+Zx17M,iv:fJRLk/Iy1nhlYWk9VUjcdy+iKrU8pHUcOW/ICh2TSz0=,tag:73ztUe3afCbmDIlTt6nG7Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Q1lXl2+saK5+kkQTzYJCa7LVIaXDRCUP4adXUiGM6g2RNtNN,iv:GBNn4Eq6gRQPDomVxAC6M1z+UzY2my3BJ9mPfcUkdfQ=,tag:BOdKPRRQxFTRb6b6nstQRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVFo5ZjNVUDJKL0VzaDVj
            MUprRGZMM1hHNlVhUWwwU1Z6WFg4aVo4SXhFCmVTTGxNRHlJcVVCS0wzSzNOd1ZO
            bm1GU1Nla1F4Y3FtamJvbU1McFBScjQKLS0tIGRWVFFrUDN4VU5VZlFabGtkWE8z
            MlMyeDZzdU9LL2QyMm1jL0dZK0VqZVkK4enVezP/yqnumyR8/IJtCorbeD9UUmY1
            IPqObhoYQxk/YrjlGB5o6daxncHI9xyv3K9oXzgzMOW3Ey209q46Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:17:21Z"
    mac: ENC[AES256_GCM,data:ku59aQYohcuADF2PIIPg1q+o25JP/GkT3+0EwGGll5L2wx/5nTXhQN9CtDWD5VM3/9HCM7S3wOCcmQouQmnC3GSMJ2P7TK7ya08LvWjZjuEguxXheJBZyybtBbc3vta2hFJ2BmHMS19ZBTSkpxvJHQq/eOrD3n5i+FtBYk4U+lg=,iv:5YCI+jLlwedn4k4o03hkwBBUFExRfM3cG7Xk+d9iUms=,tag:IZ+0dOMN40Sv0SOWayB7/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
