apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nN/+GW/GmubvblmYurxBSqKZY5naVKZoklFMktT3roc=,iv:xlQi+CmejqZz4t9tjQPplD3V2gj8v2htM/Y0zgsCb28=,tag:sZmtb+Ublr4HgAqc+cpLBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV3J2TEF3ODhiS1hVVkxD
            VEthZGxGRVFLL3QwUDExd0Z0c2E4YjhENHdJCkk1d1A2TkZ6R2djTWltUFB0UEd4
            QjlzM1B5V3pZcmYrZnJsSTRTREtMQkkKLS0tIDRDRjJ3cTZIaHpNdTVSTkZxd1M2
            VzlwVkZFcHpOeXlVZTFVNFBhajRLT1UK3Jni1G6259ovD4ndubZcLA3AS6i3Nbw9
            raQHzrL4P/999GZocvw6fJ9HyySrEgQCLKeac6jkxxUq9c+pxv0PGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:17:21Z"
    mac: ENC[AES256_GCM,data:FmUs+YhlajjMoj2tYcmfEtWJ4JjEG0z40e+r5pd1ofox6/ltn5bTEOgv8+XgCh2pCVVfjzfrHUA+Tc8gyt12HYEUFoXjhzCG9klesgdk8/pEBrwQA/eNm4WdFoj3f0G8k0mxtYBjE5aejs7ktllN3b+6Qzzr+NM0tdeTumXhF0I=,iv:wclXy1t9Eb1mNkb2KEBFdgOskEnoKJU6lJ73uyzw+sg=,tag:OhqIjY0PbG7du9zJsoinvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
