apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:p1i7JOLlzk4pZEXkGYXmTd2dWXNZyfM8D6ChX8K22PYob4TMVAsreg==,iv:TcyMrY2I+a0tS4k4xr2POoChfdAhNMUNEUcyBJJD5Gc=,tag:aQDTHr3fPjPfA4PbY8YD8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5d6095pcestzdf6zxfu6dy5tg9cddpngt40ztn24sz64qgw09uqy8anw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QjZrczJHVkxMZ21BWXd1
            MS9vWjF2UmlvUGlmY2ZTOEJMNjNmMCtJK0hjCjNxbGE2ZlcraWRUZXZjOWtHZFE2
            eUZXKzdqK3RzS2l5c2pqTFdDS2o1Wk0KLS0tIGJ3M1hCUFpxRU50VlpwRGkwMnlx
            NGpESlJ1cjhsa2JtY1NOMWZaYjdrdE0K2yyq6VKno+VrDPJ4e57VRC8niH8/YU5m
            AGFHTC08LhgyE0csdTrCDlOjPUAatB/5ZmKB65sxqrHiTQEkp0US1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T19:17:21Z"
    mac: ENC[AES256_GCM,data:MICSlrnl5XtAV4A4ULSD5hq98wHvf8xaQO4dkrmwl9ol+9jw7aWJ9y20mMgAP7oTRWMA8izCY8J/GeGBMHAlFBNuxH/53o8Gwq30FtXt9BHaLGOTewoTYQqyfGiD2XXx7Xpgn1yd+JCnzSeN5/19Q7gtPxrFfp/B9PcqelmWL2s=,iv:UvfeqpNHPM9KHV3uyiR4o0QyF1Yt86CpfD/5dKV7NSY=,tag:tna+gO7awMz3O3D/jrCgRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
